name = "wheres-my-money-cf"
main = "src/index.ts"
compatibility_date = "2024-04-04"
compatibility_flags = ["nodejs_compat"]



[env.dev]
routes = [
	{ pattern = "api-test.idencapital.no/wmm*", zone_name="idencapital.no" }
]
[env.prod]
routes = [
	{ pattern = "api.idencapital.no/wmm*", zone_name="idencapital.no" }
]