name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    secrets: inherit
    uses: "./.github/workflows/deploy-action.yml"
    with:
      target-env: dev

  deploy-staging:
    needs: deploy-dev
    secrets: inherit
    uses: "./.github/workflows/deploy-action.yml"
    with:
      target-env: stage

  deploy-prod:
    needs: deploy-staging
    secrets: inherit
    uses: "./.github/workflows/deploy-action.yml"
    with:
      target-env: prod
