name: Deploy
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.9.2
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test:ci

  deploy-dev:
    needs: test
    secrets: inherit
    uses: "./.github/workflows/deploy-action.yml"
    with:
      target-env: dev

  deploy-staging:
    needs: deploy-dev
    secrets: inherit
    uses: "./.github/workflows/deploy-action.yml"
    with:
      target-env: stage

  deploy-prod:
    needs: deploy-staging
    secrets: inherit
    uses: "./.github/workflows/deploy-action.yml"
    with:
      target-env: prod
