name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    uses: "./.github/workflows/deploy-action.yml"
    with:
      target-env: dev
    secrets: inherit

  deploy-prod:
    needs: deploy-dev
    uses: "./.github/workflows/deploy-action.yml"
    with:
      target-env: prod
    secrets: inherit
