name: Manual deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  deploy:
    secrets: inherit
    uses: "./.github/workflows/deploy-action.yml"
    with:
      target-env: ${{inputs.environment}}
